service: deploybot

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  stage: dev
  region: eu-west-2
  runtime: python2.7
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: messages/send.send
    events:
      - http:
          path: messages
          method: post
          cors: true
  # list:
  #   handler: messages/list.list
  #   events:
  #     - http:
  #         path: messages
  #         method: get
  #         cors: true
  # get:
  #   handler: messages/get.get
  #   events:
  #     - http:
  #         path: messages/{id}
  #         method: get
  #         cors: true
  # update:
  #   handler: messages/update.update
  #   events:
  #     - http:
  #         path: messages/{id}
  #         method: put
  #         cors: true
  # delete:
  #   handler: messages/delete.delete
  #   events:
  #     - http:
  #         path: messages/{id}
  #         method: delete
  #         cors: true

resources:
  Resources:
    messagesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
