version: 2
jobs:
  build:
    docker:
      - image: signalnoise/base:10.13
      # - image: signalnoise/python:10.13-2.7
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm i serverless
            npm i serverless-python-requirements
      - run:
          name: Auth keys
          command: |
            ./node_modules/.bin/serverless config credentials \
            --provider aws \
            --key $AWS_KEY \
            --secret $AWS_SECRET
      - run:
          name: Deploy
          command: ./node_modules/.bin/serverless deploy --verbose
      - run:
          name: Notify
          command: ./.circleci/notify.sh

workflows:
  version: 2
  test_and_build:
    jobs:
      - build:
          context: sn-global
