version: 2
jobs:
  build:
    docker:
      - image: signalnoise/base:10.13
      # - image: signalnoise/python:10.13-2.7
    working_directory: ~/project
    steps:
      - "[[ 1 == 1]] && circleci step halt || true" # we can't deploy from CI at the moment :/
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm ci
            pip install --upgrade pip
            apk add --no-cache --virtual .build-deps  \
              bzip2-dev \
              coreutils \
              dpkg-dev dpkg \
              findutils \
              gcc \
              gdbm-dev \
              libc-dev \
              libnsl-dev \
              libressl-dev \
              libtirpc-dev \
              linux-headers \
              make \
              ncurses-dev \
              pax-utils \
              readline-dev \
              sqlite-dev \
              tcl-dev \
              tk \
              tk-dev \
              zlib-dev \
              python2-dev \
              libffi-dev
      - run:
          name: Auth keys
          command: |
            ./node_modules/.bin/serverless config credentials \
            --provider aws \
            --key $AWS_KEY \
            --secret $AWS_SECRET
      - run:
          name: Deploy
          command: ./node_modules/.bin/serverless deploy --verbose
      - run:
          name: Notify
          command: ./.circleci/notify.sh

workflows:
  version: 2
  test_and_build:
    jobs:
      - build:
          context: sn-global
