version: 2
jobs:
  test:
    docker:
      - image: signalnoise/base:10.13
      # - image: signalnoise/python:10.13-2.7
    working_directory: ~/project
    steps:
      - run: "circleci step halt" # we can't deploy from CI at the moment :/

  build:
    docker:
      - image: signalnoise/base:10.13
    steps:
      - run: echo $ENVIRONMENT
      - run: echo $VERSION
      - run: echo $SUBDOMAIN
      - run: echo $URL

  old_build:
    docker:
      - image: signalnoise/base:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - run:
          name: Auth keys
          command: |
            ./node_modules/.bin/serverless config credentials \
            --provider aws \
            --key $AWS_KEY \
            --secret $AWS_SECRET
      - run:
          name: Deploy
          command: ./node_modules/.bin/serverless deploy --verbose

notify:
  webhooks:
    - url: https://g0iuexni0j.execute-api.eu-west-2.amazonaws.com/prod/circleci/webhook

workflows:
  version: 2
  test_and_build:
    jobs:
      - test:
          context: sn-global
