{
    u'forced': False,
    u'compare': u'https://github.com/signal-noise/deploybot/compare/c6db5144f89c...7f85d15b3c71',
    u'pusher': {
        u'name': u'marcelkornblum',
        u'email': u'marcelkornblum@users.noreply.github.com'
    },
    u'sender': {
        u'following_url': u'https://api.github.com/users/marcelkornblum/following{/other_user}',
        u'events_url': u'https://api.github.com/users/marcelkornblum/events{/privacy}',
        u'avatar_url': u'https://avatars1.githubusercontent.com/u/1162347?v=4',
        u'url': u'https://api.github.com/users/marcelkornblum',
        u'gists_url': u'https://api.github.com/users/marcelkornblum/gists{/gist_id}',
        u'html_url': u'https://github.com/marcelkornblum',
        u'subscriptions_url': u'https://api.github.com/users/marcelkornblum/subscriptions',
        u'node_id': u'MDQ6VXNlcjExNjIzNDc=',
        u'repos_url': u'https://api.github.com/users/marcelkornblum/repos',
        u'received_events_url': u'https://api.github.com/users/marcelkornblum/received_events',
        u'gravatar_id': u'',
        u'starred_url': u'https://api.github.com/users/marcelkornblum/starred{/owner}{/repo}',
        u'site_admin': False,
        u'login': u'marcelkornblum',
        u'type': u'User',
        u'id': 1162347,
        u'followers_url': u'https://api.github.com/users/marcelkornblum/followers',
        u'organizations_url': u'https://api.github.com/users/marcelkornblum/orgs'
    },
    u'repository': {
        u'issues_url': u'https://api.github.com/repos/signal-noise/deploybot/issues{/number}',
        u'deployments_url': u'https://api.github.com/repos/signal-noise/deploybot/deployments',
        u'stargazers_count': 0,
        u'forks_url': u'https://api.github.com/repos/signal-noise/deploybot/forks',
        u'mirror_url': None,
        u'subscription_url': u'https://api.github.com/repos/signal-noise/deploybot/subscription',
        u'notifications_url': u'https://api.github.com/repos/signal-noise/deploybot/notifications{?since,all,participating}',
        u'collaborators_url': u'https://api.github.com/repos/signal-noise/deploybot/collaborators{/collaborator}',
        u'updated_at': u'2018-12-21T21:04:37Z',
        u'private': True,
        u'pulls_url': u'https://api.github.com/repos/signal-noise/deploybot/pulls{/number}',
        u'issue_comment_url': u'https://api.github.com/repos/signal-noise/deploybot/issues/comments{/number}',
        u'labels_url': u'https://api.github.com/repos/signal-noise/deploybot/labels{/name}',
        u'has_wiki': True,
        u'full_name': u'signal-noise/deploybot',
        u'owner': {
            u'following_url': u'https://api.github.com/users/signal-noise/following{/other_user}',
            u'events_url': u'https://api.github.com/users/signal-noise/events{/privacy}',
            u'name': u'signal-noise',
            u'avatar_url': u'https://avatars3.githubusercontent.com/u/17909811?v=4',
            u'url': u'https://api.github.com/users/signal-noise',
            u'gists_url': u'https://api.github.com/users/signal-noise/gists{/gist_id}',
            u'subscriptions_url': u'https://api.github.com/users/signal-noise/subscriptions',
            u'html_url': u'https://github.com/signal-noise',
            u'email': u'hello@signal-noise.co.uk',
            u'node_id': u'MDEyOk9yZ2FuaXphdGlvbjE3OTA5ODEx',
            u'repos_url': u'https://api.github.com/users/signal-noise/repos',
            u'received_events_url': u'https://api.github.com/users/signal-noise/received_events',
            u'gravatar_id': u'',
            u'starred_url': u'https://api.github.com/users/signal-noise/starred{/owner}{/repo}',
            u'site_admin': False,
            u'login': u'signal-noise',
            u'type': u'Organization',
            u'id': 17909811,
            u'followers_url': u'https://api.github.com/users/signal-noise/followers',
            u'organizations_url': u'https://api.github.com/users/signal-noise/orgs'
        },
        u'statuses_url': u'https://api.github.com/repos/signal-noise/deploybot/statuses/{sha}',
        u'id': 157563029,
        u'keys_url': u'https://api.github.com/repos/signal-noise/deploybot/keys{/key_id}',
        u'description': u'Slack bot for managing CI',
        u'tags_url': u'https://api.github.com/repos/signal-noise/deploybot/tags',
        u'archived': False,
        u'downloads_url': u'https://api.github.com/repos/signal-noise/deploybot/downloads',
        u'assignees_url': u'https://api.github.com/repos/signal-noise/deploybot/assignees{/user}',
        u'contents_url': u'https://api.github.com/repos/signal-noise/deploybot/contents/{+path}',
        u'has_pages': False,
        u'git_refs_url': u'https://api.github.com/repos/signal-noise/deploybot/git/refs{/sha}',
        u'open_issues_count': 9,
        u'has_projects': True,
        u'clone_url': u'https://github.com/signal-noise/deploybot.git',
        u'watchers_count': 0,
        u'git_tags_url': u'https://api.github.com/repos/signal-noise/deploybot/git/tags{/sha}',
        u'milestones_url': u'https://api.github.com/repos/signal-noise/deploybot/milestones{/number}',
        u'languages_url': u'https://api.github.com/repos/signal-noise/deploybot/languages',
        u'size': 88,
        u'homepage': None,
        u'fork': False,
        u'commits_url': u'https://api.github.com/repos/signal-noise/deploybot/commits{/sha}',
        u'releases_url': u'https://api.github.com/repos/signal-noise/deploybot/releases{/id}',
        u'issue_events_url': u'https://api.github.com/repos/signal-noise/deploybot/issues/events{/number}',
        u'archive_url': u'https://api.github.com/repos/signal-noise/deploybot/{archive_format}{/ref}',
        u'comments_url': u'https://api.github.com/repos/signal-noise/deploybot/comments{/number}',
        u'events_url': u'https://api.github.com/repos/signal-noise/deploybot/events',
        u'contributors_url': u'https://api.github.com/repos/signal-noise/deploybot/contributors',
        u'html_url': u'https://github.com/signal-noise/deploybot',
        u'forks': 0,
        u'compare_url': u'https://api.github.com/repos/signal-noise/deploybot/compare/{base}...{head}',
        u'open_issues': 9,
        u'node_id': u'MDEwOlJlcG9zaXRvcnkxNTc1NjMwMjk=',
        u'git_url': u'git://github.com/signal-noise/deploybot.git',
        u'svn_url': u'https://github.com/signal-noise/deploybot',
        u'merges_url': u'https://api.github.com/repos/signal-noise/deploybot/merges',
        u'has_issues': True,
        u'ssh_url': u'git@github.com:signal-noise/deploybot.git',
        u'blobs_url': u'https://api.github.com/repos/signal-noise/deploybot/git/blobs{/sha}',
        u'master_branch': u'master',
        u'git_commits_url': u'https://api.github.com/repos/signal-noise/deploybot/git/commits{/sha}',
        u'hooks_url': u'https://api.github.com/repos/signal-noise/deploybot/hooks',
        u'has_downloads': True,
        u'license': None,
        u'name': u'deploybot',
        u'language': u'Python',
        u'url': u'https://github.com/signal-noise/deploybot',
        u'stargazers': 0,
        u'created_at': 1542206617,
        u'watchers': 0,
        u'pushed_at': 1545427898,
        u'forks_count': 0,
        u'default_branch': u'master',
        u'teams_url': u'https://api.github.com/repos/signal-noise/deploybot/teams',
        u'trees_url': u'https://api.github.com/repos/signal-noise/deploybot/git/trees{/sha}',
        u'organization': u'signal-noise',
        u'branches_url': u'https://api.github.com/repos/signal-noise/deploybot/branches{/branch}',
        u'subscribers_url': u'https://api.github.com/repos/signal-noise/deploybot/subscribers',
        u'stargazers_url': u'https://api.github.com/repos/signal-noise/deploybot/stargazers'
    },
    u'created': False,
    u'deleted': False,
    u'commits': [{
        u'committer': {
            u'username': u'web-flow',
            u'name': u'GitHub',
            u'email': u'noreply@github.com'
        },
        u'added': [],
        u'author': {
            u'username': u'marcelkornblum',
            u'name': u'Marcel Kornblum',
            u'email': u'marcelkornblum@users.noreply.github.com'
        },
        u'distinct': True,
        u'timestamp': u'2018-12-21T21:31:37Z',
        u'modified': [u'README.md'],
        u'url': u'https://github.com/signal-noise/deploybot/commit/7f85d15b3c71b2b3153257075c516154d8f0d32c',
        u'tree_id': u'd8d671b7bef2dd409ad72ef1f815526c7597e1be',
        u'message': u'Update README.md',
        u'removed': [],
        u'id': u'7f85d15b3c71b2b3153257075c516154d8f0d32c'
    }],
    u'after': u'7f85d15b3c71b2b3153257075c516154d8f0d32c',
    u'head_commit': {
        u'committer': {
            u'username': u'web-flow',
            u'name': u'GitHub',
            u'email': u'noreply@github.com'
        },
        u'added': [],
        u'author': {
            u'username': u'marcelkornblum',
            u'name': u'Marcel Kornblum',
            u'email': u'marcelkornblum@users.noreply.github.com'
        },
        u'distinct': True,
        u'timestamp': u'2018-12-21T21:31:37Z',
        u'modified': [u'README.md'],
        u'url': u'https://github.com/signal-noise/deploybot/commit/7f85d15b3c71b2b3153257075c516154d8f0d32c',
        u'tree_id': u'd8d671b7bef2dd409ad72ef1f815526c7597e1be',
        u'message': u'Update README.md',
        u'removed': [],
        u'id': u'7f85d15b3c71b2b3153257075c516154d8f0d32c'
    },
    u'installation': {
        u'node_id': u'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uNDkxMzUw',
        u'id': 491350
    },
    u'organization': {
        u'issues_url': u'https://api.github.com/orgs/signal-noise/issues',
        u'members_url': u'https://api.github.com/orgs/signal-noise/members{/member}',
        u'description': u'Signal Noise reinvents how people see and use data.',
        u'public_members_url': u'https://api.github.com/orgs/signal-noise/public_members{/member}',
        u'url': u'https://api.github.com/orgs/signal-noise',
        u'events_url': u'https://api.github.com/orgs/signal-noise/events',
        u'avatar_url': u'https://avatars3.githubusercontent.com/u/17909811?v=4',
        u'node_id': u'MDEyOk9yZ2FuaXphdGlvbjE3OTA5ODEx',
        u'repos_url': u'https://api.github.com/orgs/signal-noise/repos',
        u'login': u'signal-noise',
        u'id': 17909811,
        u'hooks_url': u'https://api.github.com/orgs/signal-noise/hooks'
    },
    u'ref': u'refs/heads/master',
    u'base_ref': None,
    u'before': u'c6db5144f89c442faf9db680d09c39d5f26c3052'
}
